// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OLS.Models;

#nullable disable

namespace OLS.Migrations
{
    [DbContext(typeof(OLSContext))]
    partial class OLSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OLS.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnswerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"), 1L, 1);

                    b.Property<string>("AnswerContent")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("QuestionQuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_QuestionID");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionQuestionId");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Ask", b =>
                {
                    b.Property<int>("AskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AskId"), 1L, 1);

                    b.Property<string>("AskContent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DicussDicussId")
                        .HasColumnType("int")
                        .HasColumnName("Dicuss_DicussID");

                    b.HasKey("AskId");

                    b.HasIndex("DicussDicussId");

                    b.ToTable("Ask", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"), 1L, 1);

                    b.Property<string>("BlogContent")
                        .HasColumnType("text");

                    b.Property<string>("BlogImage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BlogTagBlogTagId")
                        .HasColumnType("int")
                        .HasColumnName("BlogTag_BlogTagID");

                    b.Property<string>("BlogTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BlogTopicBlogTopicId")
                        .HasColumnType("int")
                        .HasColumnName("BlogTopic_BlogTopicID");

                    b.Property<DateTime?>("PostDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("ReadTime")
                        .HasColumnType("time");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("BlogId");

                    b.HasIndex("BlogTagBlogTagId");

                    b.HasIndex("BlogTopicBlogTopicId");

                    b.HasIndex("UserUserId");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("OLS.Models.BlogComment", b =>
                {
                    b.Property<int>("BlogCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogCommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogCommentId"), 1L, 1);

                    b.Property<int?>("BlogBlogId")
                        .HasColumnType("int")
                        .HasColumnName("Blog_BlogID");

                    b.Property<int?>("BlogCommentLevel")
                        .HasColumnType("int");

                    b.Property<string>("CommentContent")
                        .HasColumnType("text");

                    b.Property<int?>("OriginCommentId")
                        .HasColumnType("int")
                        .HasColumnName("OriginCommentID");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReplyToUser")
                        .HasColumnType("int")
                        .HasColumnName("Reply_To_User");

                    b.Property<int?>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("BlogCommentId");

                    b.HasIndex("BlogBlogId");

                    b.HasIndex("ReplyToUser");

                    b.HasIndex("UserUserId");

                    b.ToTable("BlogComment", (string)null);
                });

            modelBuilder.Entity("OLS.Models.BlogTag", b =>
                {
                    b.Property<int>("BlogTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogTagID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogTagId"), 1L, 1);

                    b.Property<string>("BlogTagName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BlogTagId");

                    b.ToTable("BlogTag", (string)null);
                });

            modelBuilder.Entity("OLS.Models.BlogTopic", b =>
                {
                    b.Property<int>("BlogTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogTopicID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogTopicId"), 1L, 1);

                    b.Property<string>("BlogTopicName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BlogTopicId");

                    b.ToTable("BlogTopic", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChapterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"), 1L, 1);

                    b.Property<string>("ChapterName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CourseCourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_CourseID");

                    b.HasKey("ChapterId");

                    b.HasIndex("CourseCourseId");

                    b.ToTable("Chapter", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<string>("CourseInfomation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CourseName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("LearningPathLearningPathId")
                        .HasColumnType("int")
                        .HasColumnName("LearningPath_LearningPathID");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.Property<string>("VideoIntro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CourseId");

                    b.HasIndex("LearningPathLearningPathId");

                    b.HasIndex("UserUserId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("OLS.Models.CourseEnrolled", b =>
                {
                    b.Property<int>("CourseEnrolledId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseEnrolledID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseEnrolledId"), 1L, 1);

                    b.Property<int>("CourseCourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_CourseID");

                    b.Property<DateTime?>("EnrolledDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("CourseEnrolledId");

                    b.HasIndex("CourseCourseId");

                    b.HasIndex("UserUserId");

                    b.ToTable("CourseEnrolled", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Dicuss", b =>
                {
                    b.Property<int>("DicussId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DicussID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DicussId"), 1L, 1);

                    b.Property<int>("LessonLessonId")
                        .HasColumnType("int")
                        .HasColumnName("Lesson_LessonID");

                    b.HasKey("DicussId");

                    b.HasIndex("LessonLessonId");

                    b.ToTable("Dicuss", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"), 1L, 1);

                    b.Property<int>("CourseCourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_CourseID");

                    b.Property<string>("FeedbackContent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RateStar")
                        .HasColumnType("int");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CourseCourseId");

                    b.HasIndex("UserUserId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("OLS.Models.LearningPath", b =>
                {
                    b.Property<int>("LearningPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LearningPathID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningPathId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LearningPathName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("LearningPathId");

                    b.ToTable("LearningPath", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LessonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"), 1L, 1);

                    b.Property<int>("ChapterChapterId")
                        .HasColumnType("int")
                        .HasColumnName("Chapter_ChapterID");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Video")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LessonId");

                    b.HasIndex("ChapterChapterId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("OLS.Models.LikeComment", b =>
                {
                    b.Property<int>("BlogCommentBlogCommentId")
                        .HasColumnType("int")
                        .HasColumnName("BlogComment_BlogCommentID");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasIndex("BlogCommentBlogCommentId");

                    b.HasIndex("UserUserId");

                    b.ToTable("LikeComment", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"), 1L, 1);

                    b.Property<int>("ChapterChapterId")
                        .HasColumnType("int")
                        .HasColumnName("Chapter_ChapterID");

                    b.Property<string>("NoteContent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("NoteId");

                    b.HasIndex("ChapterChapterId");

                    b.HasIndex("UserUserId");

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuizQuizId")
                        .HasColumnType("int")
                        .HasColumnName("Quiz_QuizID");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizQuizId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuizID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"), 1L, 1);

                    b.Property<int>("ChapterChapterId")
                        .HasColumnType("int")
                        .HasColumnName("Chapter_ChapterID");

                    b.HasKey("QuizId");

                    b.HasIndex("ChapterChapterId");

                    b.ToTable("Quiz", (string)null);
                });

            modelBuilder.Entity("OLS.Models.ReceiveNotification", b =>
                {
                    b.Property<int>("ReceiveNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReceiveNotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiveNotificationId"), 1L, 1);

                    b.Property<int>("CourseCourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_CourseID");

                    b.Property<int>("SendNotificationSendNotificationId")
                        .HasColumnType("int")
                        .HasColumnName("SendNotification_SendNotificationID");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("ReceiveNotificationId");

                    b.HasIndex("CourseCourseId");

                    b.HasIndex("SendNotificationSendNotificationId");

                    b.HasIndex("UserUserId");

                    b.ToTable("ReceiveNotification", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyId"), 1L, 1);

                    b.Property<int?>("AskAskId")
                        .HasColumnType("int")
                        .HasColumnName("Ask_AskID");

                    b.Property<string>("ReplyContent")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ReplyId");

                    b.HasIndex("AskAskId");

                    b.ToTable("Reply", (string)null);
                });

            modelBuilder.Entity("OLS.Models.SaveBlog", b =>
                {
                    b.Property<int>("BlogBlogId")
                        .HasColumnType("int")
                        .HasColumnName("Blog_BlogID");

                    b.Property<int>("SaveBlogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SavedDay")
                        .HasColumnType("datetime");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasIndex("BlogBlogId");

                    b.HasIndex("UserUserId");

                    b.ToTable("SaveBlog", (string)null);
                });

            modelBuilder.Entity("OLS.Models.SaveLike", b =>
                {
                    b.Property<int>("BlogBlogId")
                        .HasColumnType("int")
                        .HasColumnName("Blog_BlogID");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasIndex("BlogBlogId");

                    b.HasIndex("UserUserId");

                    b.ToTable("SaveLike", (string)null);
                });

            modelBuilder.Entity("OLS.Models.SendNotification", b =>
                {
                    b.Property<int>("SendNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SendNotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SendNotificationId"), 1L, 1);

                    b.Property<int?>("CourseCourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_CourseID");

                    b.Property<string>("NotificationContent")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int?>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_UserID");

                    b.HasKey("SendNotificationId");

                    b.HasIndex("CourseCourseId");

                    b.HasIndex("UserUserId");

                    b.ToTable("SendNotification", (string)null);
                });

            modelBuilder.Entity("OLS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("CodeVerify")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FacebookID");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Github")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GithubId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GithubID");

                    b.Property<string>("GmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GmailID");

                    b.Property<string>("Image")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleRoleId")
                        .HasColumnType("int")
                        .HasColumnName("UserRole_RoleID");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleRoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("OLS.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("OLS.Models.Answer", b =>
                {
                    b.HasOne("OLS.Models.Question", "QuestionQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Answer_Question");

                    b.Navigation("QuestionQuestion");
                });

            modelBuilder.Entity("OLS.Models.Ask", b =>
                {
                    b.HasOne("OLS.Models.Dicuss", "DicussDicuss")
                        .WithMany("Asks")
                        .HasForeignKey("DicussDicussId")
                        .IsRequired()
                        .HasConstraintName("FK_Ask_Dicuss");

                    b.Navigation("DicussDicuss");
                });

            modelBuilder.Entity("OLS.Models.Blog", b =>
                {
                    b.HasOne("OLS.Models.BlogTag", "BlogTagBlogTag")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogTagBlogTagId")
                        .IsRequired()
                        .HasConstraintName("FK_Blog_BlogTag");

                    b.HasOne("OLS.Models.BlogTopic", "BlogTopicBlogTopic")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogTopicBlogTopicId")
                        .IsRequired()
                        .HasConstraintName("FK_Blog_BlogTopic");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("Blogs")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Blog_User");

                    b.Navigation("BlogTagBlogTag");

                    b.Navigation("BlogTopicBlogTopic");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.BlogComment", b =>
                {
                    b.HasOne("OLS.Models.Blog", "BlogBlog")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogBlogId")
                        .HasConstraintName("FK_BlogComment_Blog");

                    b.HasOne("OLS.Models.User", "ReplyToUserNavigation")
                        .WithMany("BlogCommentReplyToUserNavigations")
                        .HasForeignKey("ReplyToUser")
                        .HasConstraintName("FK_BlogComment_User1");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("BlogCommentUserUsers")
                        .HasForeignKey("UserUserId")
                        .HasConstraintName("FK_BlogComment_User");

                    b.Navigation("BlogBlog");

                    b.Navigation("ReplyToUserNavigation");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.Chapter", b =>
                {
                    b.HasOne("OLS.Models.Course", "CourseCourse")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseCourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Chapter_Course");

                    b.Navigation("CourseCourse");
                });

            modelBuilder.Entity("OLS.Models.Course", b =>
                {
                    b.HasOne("OLS.Models.LearningPath", "LearningPathLearningPath")
                        .WithMany("Courses")
                        .HasForeignKey("LearningPathLearningPathId")
                        .IsRequired()
                        .HasConstraintName("FK_Course_LearningPath");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("Courses")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Course_User");

                    b.Navigation("LearningPathLearningPath");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.CourseEnrolled", b =>
                {
                    b.HasOne("OLS.Models.Course", "CourseCourse")
                        .WithMany("CourseEnrolleds")
                        .HasForeignKey("CourseCourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseEnrolled_Course");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("CourseEnrolleds")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseEnrolled_User");

                    b.Navigation("CourseCourse");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.Dicuss", b =>
                {
                    b.HasOne("OLS.Models.Lesson", "LessonLesson")
                        .WithMany("Dicusses")
                        .HasForeignKey("LessonLessonId")
                        .IsRequired()
                        .HasConstraintName("FK_Dicuss_Lesson");

                    b.Navigation("LessonLesson");
                });

            modelBuilder.Entity("OLS.Models.Feedback", b =>
                {
                    b.HasOne("OLS.Models.Course", "CourseCourse")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseCourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Course");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_User");

                    b.Navigation("CourseCourse");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.Lesson", b =>
                {
                    b.HasOne("OLS.Models.Chapter", "ChapterChapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_Chapter");

                    b.Navigation("ChapterChapter");
                });

            modelBuilder.Entity("OLS.Models.LikeComment", b =>
                {
                    b.HasOne("OLS.Models.BlogComment", "BlogCommentBlogComment")
                        .WithMany()
                        .HasForeignKey("BlogCommentBlogCommentId")
                        .IsRequired()
                        .HasConstraintName("FK_LikeComment_BlogComment");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany()
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_LikeComment_User");

                    b.Navigation("BlogCommentBlogComment");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.Note", b =>
                {
                    b.HasOne("OLS.Models.Chapter", "ChapterChapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_Note_Chapter");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("Notes")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Note_User");

                    b.Navigation("ChapterChapter");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.Question", b =>
                {
                    b.HasOne("OLS.Models.Quiz", "QuizQuiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizQuizId")
                        .IsRequired()
                        .HasConstraintName("FK_Question_Quiz");

                    b.Navigation("QuizQuiz");
                });

            modelBuilder.Entity("OLS.Models.Quiz", b =>
                {
                    b.HasOne("OLS.Models.Chapter", "ChapterChapter")
                        .WithMany("Quizzes")
                        .HasForeignKey("ChapterChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_Quiz_Chapter");

                    b.Navigation("ChapterChapter");
                });

            modelBuilder.Entity("OLS.Models.ReceiveNotification", b =>
                {
                    b.HasOne("OLS.Models.Course", "CourseCourse")
                        .WithMany("ReceiveNotifications")
                        .HasForeignKey("CourseCourseId")
                        .IsRequired()
                        .HasConstraintName("FK_ReceiveNotification_Course");

                    b.HasOne("OLS.Models.SendNotification", "SendNotificationSendNotification")
                        .WithMany("ReceiveNotifications")
                        .HasForeignKey("SendNotificationSendNotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_ReceiveNotification_SendNotification");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("ReceiveNotifications")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ReceiveNotification_User");

                    b.Navigation("CourseCourse");

                    b.Navigation("SendNotificationSendNotification");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.Reply", b =>
                {
                    b.HasOne("OLS.Models.Ask", "AskAsk")
                        .WithMany("Replies")
                        .HasForeignKey("AskAskId")
                        .HasConstraintName("FK_Reply_Ask");

                    b.Navigation("AskAsk");
                });

            modelBuilder.Entity("OLS.Models.SaveBlog", b =>
                {
                    b.HasOne("OLS.Models.Blog", "BlogBlog")
                        .WithMany()
                        .HasForeignKey("BlogBlogId")
                        .IsRequired()
                        .HasConstraintName("FK_SaveBlog_Blog");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany()
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_SaveBlog_User");

                    b.Navigation("BlogBlog");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.SaveLike", b =>
                {
                    b.HasOne("OLS.Models.Blog", "BlogBlog")
                        .WithMany()
                        .HasForeignKey("BlogBlogId")
                        .IsRequired()
                        .HasConstraintName("FK_SaveLike_Blog");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany()
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("FK_SaveLike_User");

                    b.Navigation("BlogBlog");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.SendNotification", b =>
                {
                    b.HasOne("OLS.Models.Course", "CourseCourse")
                        .WithMany("SendNotifications")
                        .HasForeignKey("CourseCourseId")
                        .HasConstraintName("FK_SendNotification_Course");

                    b.HasOne("OLS.Models.User", "UserUser")
                        .WithMany("SendNotifications")
                        .HasForeignKey("UserUserId")
                        .HasConstraintName("FK_SendNotification_User");

                    b.Navigation("CourseCourse");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("OLS.Models.User", b =>
                {
                    b.HasOne("OLS.Models.UserRole", "UserRoleRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_UserRole");

                    b.Navigation("UserRoleRole");
                });

            modelBuilder.Entity("OLS.Models.Ask", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("OLS.Models.Blog", b =>
                {
                    b.Navigation("BlogComments");
                });

            modelBuilder.Entity("OLS.Models.BlogTag", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("OLS.Models.BlogTopic", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("OLS.Models.Chapter", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Notes");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("OLS.Models.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("CourseEnrolleds");

                    b.Navigation("Feedbacks");

                    b.Navigation("ReceiveNotifications");

                    b.Navigation("SendNotifications");
                });

            modelBuilder.Entity("OLS.Models.Dicuss", b =>
                {
                    b.Navigation("Asks");
                });

            modelBuilder.Entity("OLS.Models.LearningPath", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("OLS.Models.Lesson", b =>
                {
                    b.Navigation("Dicusses");
                });

            modelBuilder.Entity("OLS.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("OLS.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OLS.Models.SendNotification", b =>
                {
                    b.Navigation("ReceiveNotifications");
                });

            modelBuilder.Entity("OLS.Models.User", b =>
                {
                    b.Navigation("BlogCommentReplyToUserNavigations");

                    b.Navigation("BlogCommentUserUsers");

                    b.Navigation("Blogs");

                    b.Navigation("CourseEnrolleds");

                    b.Navigation("Courses");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notes");

                    b.Navigation("ReceiveNotifications");

                    b.Navigation("SendNotifications");
                });

            modelBuilder.Entity("OLS.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
